"""Generate .env.example files from existing .env files by stripping secret values."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from envdiff.masker import is_secret_key
from envdiff.parser import parse_env_file


@dataclass
class TemplateResult:
    path: str
    keys_written: list[str] = field(default_factory=list)
    keys_blanked: list[str] = field(default_factory=list)

    def summary(self) -> str:
        total = len(self.keys_written) + len(self.keys_blanked)
        return (
            f"Template written to '{self.path}': "
            f"{total} keys ({len(self.keys_blanked)} blanked)."
        )


def generate_template(
    source: str,
    output: Optional[str] = None,
    secret_keywords: Optional[list[str]] = None,
    placeholder: str = "",
    keep_comments: bool = True,
) -> TemplateResult:
    """Read *source* .env file and write a sanitised template.

    Secret keys have their values replaced with *placeholder* (default: empty).
    Non-secret keys retain their original values.
    """
    source_path = Path(source)
    if output is None:
        output = str(source_path.with_suffix(".example"))

    env_vars = parse_env_file(source)

    result = TemplateResult(path=output)
    lines: list[str] = []

    if keep_comments:
        lines.append("# Generated by envdiff — do not store real secrets here")
        lines.append("")

    for key, value in env_vars.items():
        if is_secret_key(key, secret_keywords):
            lines.append(f"{key}={placeholder}")
            result.keys_blanked.append(key)
        else:
            lines.append(f"{key}={value}")
            result.keys_written.append(key)

    Path(output).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return result
